version: '3.2'

services:
  webspa:
    image: tensor-snake/webspa
    build:
      context: .
      dockerfile: src/WebApps/WebSPA/Dockerfile
    volumes:
      - './src/WebApps/WebSPA:/usr/src/app'
      - '/usr/src/app/node_modules'
    depends_on:
      - identity.api
      - score.api

  identity.api:
    image: tensor-snake/identity.api
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  score.api:
    image: tensor-snake/score.api
    build:
      context: .
      dockerfile: src/Services/Scores/Score.API/Dockerfile

    depends_on:
      - identity.api

