version: 2

general:
  branches:
    only:
     - master



jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
         heroku --version
         heroku update

      # build image
      - run: |
         docker info
         docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

      # print heroku help
      - run: |
         heroku help container

      # print image
      - run: |
         docker images

      # deploy the image
      - run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag tensor-snake/webspa registry.heroku.com/$HEROKU_WEB_SPA_NAME/web
         docker push registry.heroku.com/$HEROKU_WEB_SPA_NAME/web

      # release images 
      - run: |
         heroku container:release web --app $HEROKU_WEB_SPA_NAME
      